apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-coffeehouse
  namespace: {{ $.Release.Namespace }}
  labels:
    app: go-coffeehouse
    chart_name: {{ .Chart.Name }}
    chart_version: {{ .Chart.Version }}
    service: {{ .Chart.Name }}
    team: {{ .Values.team }}
spec:
  replicas: {{ $.Values.replicas.javaCoffeehouse }}
  revisionHistoryLimit: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: go-coffeehouse
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: go-coffeehouse
      labels:
        app: go-coffeehouse
        chart_name: {{ .Chart.Name }}
        service: {{ .Chart.Name }}
        team: {{ .Values.team }}
      annotations:
        ad.datadoghq.com/go-coffeehouse.logs: |
          [
            {
              "source": "go",
              "service": "{{ .Chart.Name }}-coffeehouse"
            }
          ]
    spec:
      containers:
      - name: go-coffeehouse
        image: "{{ $.Values.global.docker.registry }}/{{ $.Values.images.goCoffeehouse.name }}:{{ $.Values.image.tag }}"
        ports:
        - containerPort: 8080
        resources:
{{ toYaml $.Values.deployment.resources.goCoffeehouse | indent 10 }}
        volumeMounts:
{{ toYaml $.Values.dogstatsd_custom_socket.volumeMounts | indent 8 }}
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "{{ $.Values.trace_port }}"
        - name: PORT
          value: "8080"
{{ toYaml $.Values.dogstatsd_custom_socket.env | indent 8 }}
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 10
      volumes:
{{ toYaml $.Values.dogstatsd_custom_socket.volumes | indent 8 }}
