apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-api-gateway
  namespace: {{ $.Release.Namespace }}
  labels:
    app: js-api-gateway
    chart_name: {{ .Chart.Name }}
    chart_version: {{ .Chart.Version }}
    service: {{ .Chart.Name }}
    team: {{ .Values.team }}
spec:
  replicas: {{ $.Values.replicas.jsApiGateway }}
  revisionHistoryLimit: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: js-api-gateway
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: js-api-gateway
      labels:
        app: js-api-gateway
        chart_name: {{ .Chart.Name }}
        service: {{ .Chart.Name }}
        team: {{ .Values.team }}
      annotations:
        ad.datadoghq.com/js-api-gateway.logs: |
          [
            {
              "source": "nodejs",
              "service": "{{ .Chart.Name }}-js-api-gateway"
            }
          ]
    spec:
      containers:
      - name: js-api-gateway
        image: "{{ $.Values.global.docker.registry }}/{{ $.Values.images.jsApiGateway.name }}:{{ $.Values.image.tag }}-api-gateway"
        ports:
        - containerPort: 8080
        resources:
{{ toYaml $.Values.deployment.resources.jsApiGateway | indent 10 }}
        volumeMounts:
{{ toYaml $.Values.dogstatsd_custom_socket.volumeMounts | indent 8 }}
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "{{ $.Values.trace_port }}"
        - name: AUTH_SERVER_URL
          value: "http://js-auth:8080"
        - name: USER_SERVER_URL
          value: "http://js-user:8080"
{{ toYaml $.Values.dogstatsd_custom_socket.env | indent 8 }}
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 2
          periodSeconds: 10
      volumes:
{{ toYaml $.Values.dogstatsd_custom_socket.volumes | indent 8 }}
