apiVersion: v1
kind: Service
metadata:
  name: js-user
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart_name: {{ .Chart.Name }}
    chart_version: {{ .Chart.Version }}
    service: {{ .Chart.Name }}
    team: {{ .Values.team }}
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: js-user
  clusterIP: None
