apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart_name: {{ .Chart.Name }}
    chart_version: {{ .Chart.Version }}
    service: {{ .Chart.Name }}
    team: {{ .Values.team }}
spec:
  ports:
  - name: memcached
    port: 11211
  selector:
    app: memcached
  clusterIP: None
