apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: {{ $.Release.Namespace }}
  labels:
    app: mongo
    chart_name: {{ .Chart.Name }}
    chart_version: {{ .Chart.Version }}
    service: {{ .Chart.Name }}
    team: {{ .Values.team }}
spec:
  replicas: {{ $.Values.replicas.mongo }}
  revisionHistoryLimit: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: mongo
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
        chart_name: {{ .Chart.Name }}
        service: {{ .Chart.Name }}
        team: {{ .Values.team }}
      annotations:
        ad.datadoghq.com/mongo.logs: |
          [
            {
              "service": {{ $.Chart.Name | quote }},
              "source": "mongodb"
            }
          ]
    spec:
      # no-TolerationLinter
      containers:
      - name: mongo
        image: "{{ $.Values.images.mongo.name }}:{{ $.Values.images.mongo.tag }}"
        resources:
{{ toYaml $.Values.deployment.resources.mongo | indent 10 }}
        volumeMounts:
{{ toYaml $.Values.dogstatsd_custom_socket.volumeMounts | indent 8 }}
        env:
{{ toYaml $.Values.dogstatsd_custom_socket.env | indent 8 }}
        ports:
        - containerPort: 27017
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mongo --eval 'rs.status()'"
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 3
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mongo --eval 'rs.status()'"
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 10
      volumes:
{{ toYaml $.Values.dogstatsd_custom_socket.volumes | indent 8 }}
