apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart_name: {{ .Chart.Name }}
    chart_version: {{ .Chart.Version }}
    service: {{ .Chart.Name }}
    team: {{ .Values.team }}
spec:
  ports:
  - name: mongo
    port: 27017
  selector:
    app: mongo
  clusterIP: None
