apiVersion: v1
kind: Service
metadata:
  name: php-coffeehouse-backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart_name: {{ .Chart.Name }}
    chart_version: {{ .Chart.Version }}
    service: {{ .Chart.Name }}
    team: {{ .Values.team }}
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: php-coffeehouse-backend
  clusterIP: None
